/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprojectpet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaprojectpet.Login_for_employee_admin.getMd5;
import static javaprojectpet.dao.ConnectDB.ketNoi;
import javaprojectpet.entitys.DatLich;
import javaprojectpet.entitys.KhachHang;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Linh & Phong
 */
public class Frame_Order_Add extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Order_Add
     */
    Connection con;
    PreparedStatement pst; 
    ResultSet rs; 
     DefaultTableModel model;
    DefaultTableModel model1;
    DefaultTableModel model2;
    public Frame_Order_Add() {
        initComponents();
        this.setTitle("Thêm phần đặt lịch");
        this.setLocationRelativeTo(null);
         model = (DefaultTableModel)jTableGuest.getModel();
        model1 = (DefaultTableModel)jTablePet.getModel();
        model2 = (DefaultTableModel)JTablePetCompareGuest.getModel();
        try {
            con = ketNoi();
        } catch (Exception e) {
            System.out.println(e);
        }
        
        fill_idthucung();
        fill_idkhach();
        showTableGuest();
        showTablePet();
        choiceIdThuCung.setVisible(false);
        choiceIDGuest.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
         
        
        
        jTableGuest.setRowHeight(40);
        jTablePet.setRowHeight(40);
        JTablePetCompareGuest.setRowHeight(40);
          
    }
public void showTableGuest(){
        try{

        java.sql.Connection con = ketNoi();
        PreparedStatement ps = con.prepareStatement("select * from khachhang");
        java.sql.ResultSet rs=ps.executeQuery();
        DefaultTableModel tm = (DefaultTableModel)jTableGuest.getModel();
        tm.setRowCount(0);
        while(rs.next()){
            
            Object o[]={rs.getInt("id_khachhang"), rs.getString("ten_khachhang"), rs.getString("Email"), rs.getString("sdt_khachhang"), rs.getString("ngaythem_khachhang"), rs.getString("Email")};
            
            tm.addRow(o);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
public void showTablePet(){
        try{
         
        java.sql.Connection con = ketNoi();
        PreparedStatement ps = con.prepareStatement("select * from thucung");
        java.sql.ResultSet rs=ps.executeQuery();
        DefaultTableModel tm = (DefaultTableModel)jTablePet.getModel();
        tm.setRowCount(0);
        while(rs.next()){
            
            Object o[]={rs.getInt("id_thucung"), rs.getString("name_thucung"), rs.getString("loaidongvat_thucung"), rs.getInt("tuoi_thucung")};
            
            tm.addRow(o);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

private void fill_idthucung(){
     try{
         String sql = "select thucung.id_thucung from thucung"; // gan chuoi cho bien sql
         pst=con.prepareStatement(sql); // thuc hien cau lenh truy van 
         rs=pst.executeQuery(); //chua cau lenh truy van 
         
         while(rs.next()){
             String name = rs.getString("id_thucung");
             choiceIdThuCung.addItem(name);
         }
         
     }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
     }
 }
private void fill_idkhach(){
     try{
         String sql = "select khachhang.id_khachhang from khachhang";
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         
         while(rs.next()){
             String name = rs.getString("id_khachhang");
             choiceIDGuest.addItem(name);
         }
         
     }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
     }
    
 }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGuest = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePet = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        choiceIdThuCung = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        choiceIDGuest = new java.awt.Choice();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextFieldTrieuChung = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabelGuestName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNamePet = new javax.swing.JLabel();
        jTextFieldTimKiemKhachHang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTimKiemQuanHe = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldTimKiemThuCung = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTablePetCompareGuest = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableGuest.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTableGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID khách hàng", "Tên khách hàng", "Email", "Số điện thoại", "Ngày thêm khách hàng"
            }
        ));
        jTableGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGuestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGuest);

        jTablePet.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTablePet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID thú cưng", "Tên thú cưng", "Loại động vật", "Tuổi"
            }
        ));
        jTablePet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePet);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        choiceIdThuCung.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Thú cưng");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID khách");

        choiceIDGuest.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        choiceIDGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choiceIDGuestMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Triệu chứng");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Chưa Tiến Hành");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Đang Tiến Hành");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Đã Tiến Hành");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Hủy");

        jButtonAdd.setBackground(new java.awt.Color(153, 255, 153));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jButtonAdd.setText("Thêm ");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(255, 102, 102));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 47)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jTextFieldTrieuChung.setColumns(20);
        jTextFieldTrieuChung.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextFieldTrieuChung.setRows(5);
        jScrollPane4.setViewportView(jTextFieldTrieuChung);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên khách");

        jLabelGuestName.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabelGuestName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên thú cưng");

        jLabelNamePet.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabelNamePet.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldTimKiemKhachHang.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTextFieldTimKiemKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTimKiemKhachHangKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tìm kiếm thông tin khách hàng ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tìm kiếm thông tin quan hệ");

        jTextFieldTimKiemQuanHe.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTextFieldTimKiemQuanHe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTimKiemQuanHeKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tìm kiếm thông tin thú cưng");

        jTextFieldTimKiemThuCung.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTextFieldTimKiemThuCung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTimKiemThuCungKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choiceIDGuest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choiceIdThuCung, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNamePet, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButtonClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addGap(213, 213, 213))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jRadioButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jRadioButton4))))
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTextFieldTimKiemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTimKiemThuCung, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldTimKiemQuanHe, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButtonBack)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(choiceIdThuCung, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)))
                        .addComponent(choiceIDGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel7)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNamePet, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel8)))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonClear))
                .addGap(37, 37, 37)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTimKiemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTimKiemThuCung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldTimKiemQuanHe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel4.setBackground(new java.awt.Color(110, 89, 222));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 54)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thông tin thêm đặt lịch");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ĐặtLịch/Thêm Đặt Lịch");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(jLabel9)))
                .addContainerGap(547, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(49, 49, 49)
                .addComponent(jLabel9)
                .addGap(39, 39, 39))
        );

        JTablePetCompareGuest.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        JTablePetCompareGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID khách hàng", "Tên khách hàng", "ID thú cưng", "Tên thú cưng"
            }
        ));
        JTablePetCompareGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTablePetCompareGuestMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTablePetCompareGuest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        
        jTextFieldTrieuChung.setText("");
        jLabelGuestName.setText("");
        jLabelNamePet.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        Frame_Order_Add frameorderadd = new Frame_Order_Add();
         
         String id_thucung = choiceIdThuCung.getSelectedItem().toString();
         String id_khach = choiceIDGuest.getSelectedItem().toString();
         String TrieuChung = jTextFieldTrieuChung.getText();
         
         DatLich datlich = new DatLich(id_khach, id_thucung, TrieuChung);
         
         if(jTextFieldTrieuChung.getText().trim().isEmpty() 
                 || buttonGroup1.isSelected(null)
               || jLabelGuestName.getText().trim().isEmpty()
                || jLabelNamePet.getText().trim().isEmpty()){ 
           JOptionPane.showMessageDialog(frameorderadd, "Chưa điền đầy đủ");
        }else{
             
             try {
              Connection con =ketNoi();
            Statement stm = con.createStatement();
          String sql1="select * from thucung where id_thucung='"+datlich.getId_thucung()+"' and id_khachhang_thucung='"+datlich.getId_khachhang()+"'";
           ResultSet rs =stm.executeQuery(sql1); //tro den dong lenh sql va chay cau lenh do
           if(rs.next()){ //neu co thong tin trong bang 
                //co  thong tin trung lap trong code sql se duoc them vao
              
                 JOptionPane.showMessageDialog(frameorderadd, "Thêm thành công!!. Sẽ Chuyển Trang trong 2 giây nữa.");
        try {
            Thread.sleep(2000);//cho 2 giay
        } catch (InterruptedException ex) {
            Logger.getLogger(Frame_Guest_Add.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.util.Date date=new java.util.Date(); //them doi tuong date

             java.sql.Date sqlDate=new java.sql.Date(date.getTime()); //lay thoi gian bay gio
             
             String sql = "INSERT INTO `ql_thucungcare`.`datlich`(`thoigian_datlich`,`id_khachhang`,`id_thucung_datlich`,`trieuchung_datlich`,`type`) VALUES (?,?,?,?,?)";
             try{
                 pst = con.prepareStatement(sql); // khởi tạo dòng lệnh sql
//                  pst.setInt(2, Integer.parseInt(jTextFieldPhoNumGue.getText()));
                    pst.setDate(1, sqlDate);//cứ mỗi phần tử lần lượt trong tham số ?
                    pst.setString(2, datlich.getId_khachhang());
//  pst.setString(4, dateinput);
                    
                    
//                  pst.setString(1, jTextFieldGuestName.getText());
                pst.setString(3, datlich.getId_thucung());
//                   pst.setString(3, jTextFieldDistrict.getText());
                pst.setString(4, datlich.getTrieuchung());
               if(jRadioButton1.isSelected()){
                       pst.setInt(5, 1);
                   }else if(jRadioButton2.isSelected()){
                       pst.setInt(5, 2);
                   }else if(jRadioButton3.isSelected()){
                       pst.setInt(5, 3);
                   }else if(jRadioButton4.isSelected()){
                       pst.setInt(5, 4);
                   }
                   
                    pst.executeUpdate(); //chạy dòng lệnh sql
             }catch (Exception e) {
                 System.out.println(e);
                // TODO: handle exception
    }
        new Frame_Order_Watch().setVisible(true);
        dispose();
            }else{
                //khong ton tai thong tin nhap vao se hien ra:
                JOptionPane.showMessageDialog(this, "Không có mối quan hệ giữa khách hàng và thú cưng.");
                
//                Login_for_employee_admin ln=new Login_for_employee_admin();
//                ln.show();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Frame_Order_Add.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Frame_Order_Add.class.getName()).log(Level.SEVERE, null, ex);
        }
      
             
             
         }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        new Frame_Order_Watch().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTableGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGuestMouseClicked
        // TODO add your handling code here:

            int row = jTableGuest.getSelectedRow();
        TableModel model=jTableGuest.getModel();
        String value =  (jTableGuest.getModel().getValueAt(row, 0).toString());
 try{
          
        java.sql.Connection con = ketNoi();
        PreparedStatement ps = con.prepareStatement("SELECT tc.id_khachhang_thucung, kh.ten_khachhang, tc.id_thucung, tc.name_thucung FROM thucung as tc LEFT JOIN khachhang as kh ON tc.id_khachhang_thucung = kh.id_khachhang WHERE kh.id_khachhang="+value);
        java.sql.ResultSet rs=ps.executeQuery();
        DefaultTableModel tm = (DefaultTableModel)JTablePetCompareGuest.getModel();
        tm.setRowCount(0);
        while(rs.next()){
            Object o[]={rs.getInt("tc.id_khachhang_thucung"), rs.getString("kh.ten_khachhang"), rs.getInt("tc.id_thucung"), rs.getString("tc.name_thucung")};
            tm.addRow(o);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
          
    }//GEN-LAST:event_jTableGuestMouseClicked

    private void jTablePetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePetMouseClicked
        // TODO add your handling code here:
         int index=jTablePet.getSelectedRow();
             TableModel model=jTablePet.getModel();
        choiceIdThuCung.select(model.getValueAt(index, 0).toString());
    }//GEN-LAST:event_jTablePetMouseClicked

    private void JTablePetCompareGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTablePetCompareGuestMouseClicked
        // TODO add your handling code here:
                 int index=JTablePetCompareGuest.getSelectedRow();
            //lay vi tri cua dong thu bao nhieu ma minh nhap vao
             TableModel model=JTablePetCompareGuest.getModel(); //lay thong tin cua bang
        choiceIDGuest.select(model.getValueAt(index, 0).toString()); 
        //lay du lieu trong vi tri cua dong ma minh nhan vao va cot duoc chi dinh trong code
        choiceIdThuCung.select(model.getValueAt(index, 2).toString());
        jLabelGuestName.setText(model.getValueAt(index, 1).toString());
        jLabelNamePet.setText(model.getValueAt(index, 3).toString());
    }//GEN-LAST:event_JTablePetCompareGuestMouseClicked

    private void choiceIDGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choiceIDGuestMouseClicked
        // TODO add your handling code here:
                String tmp = choiceIDGuest.getSelectedItem().toString();
                 String sql = "SELECT * FROM khachhang WHERE khachhang.id_khachhang =?";
                try{
                    pst = con.prepareStatement(sql);
                    pst.setString(1, tmp);
                    rs = pst.executeQuery();
                    if(rs.next()){
                        String addName = rs.getString("ten_khachhang");
                        jLabelGuestName.setText(addName);
                    }
                } catch (SQLException ex) {
            Logger.getLogger(Frame_Order_Add.class.getName()).log(Level.SEVERE, null, ex);
        }
//                String name = state.getString ()
        
    }//GEN-LAST:event_choiceIDGuestMouseClicked
private void FilterKhachHang(String query){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model); 
        jTableGuest.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    private void jTextFieldTimKiemKhachHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemKhachHangKeyTyped
        // TODO add your handling code here:
        String query = jTextFieldTimKiemKhachHang.getText();
        if(query != null && query.length() > 0){
            FilterKhachHang(query);
        }
    }//GEN-LAST:event_jTextFieldTimKiemKhachHangKeyTyped
private void FilterQuanHe(String query){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model2); 
        JTablePetCompareGuest.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    private void jTextFieldTimKiemQuanHeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemQuanHeKeyTyped
        // TODO add your handling code here:
         String query = jTextFieldTimKiemQuanHe.getText();
        if(query != null && query.length() > 0){
            FilterQuanHe(query);
        }
    }//GEN-LAST:event_jTextFieldTimKiemQuanHeKeyTyped
private void FilterThuCung(String query){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model1); 
        jTablePet.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    private void jTextFieldTimKiemThuCungKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemThuCungKeyTyped
        // TODO add your handling code here:
         String query = jTextFieldTimKiemThuCung.getText();
        if(query != null && query.length() > 0){
            FilterThuCung(query);
        }
    }//GEN-LAST:event_jTextFieldTimKiemThuCungKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Order_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Order_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Order_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Order_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Order_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablePetCompareGuest;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Choice choiceIDGuest;
    private java.awt.Choice choiceIdThuCung;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGuestName;
    private javax.swing.JLabel jLabelNamePet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableGuest;
    private javax.swing.JTable jTablePet;
    private javax.swing.JTextField jTextFieldTimKiemKhachHang;
    private javax.swing.JTextField jTextFieldTimKiemQuanHe;
    private javax.swing.JTextField jTextFieldTimKiemThuCung;
    private javax.swing.JTextArea jTextFieldTrieuChung;
    // End of variables declaration//GEN-END:variables
}
