/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaprojectpet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaprojectpet.dao.ConnectDB.ketNoi;
import javaprojectpet.entitys.ChamSoc;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author nhi
 */
public class Frame_TimeCare_Add extends javax.swing.JFrame {

    /**
     * Creates new form Frame_TimeCare_Add
     */
    Connection con;
    PreparedStatement pst; 
    ResultSet rs; 
    DefaultTableModel model; 
    DefaultTableModel model1;
    public Frame_TimeCare_Add() {
        initComponents();
        this.setTitle("Thêm thông tin chăm sóc thú cưng"); 
        this.setLocationRelativeTo(null);
        model1 = (DefaultTableModel)jTableDatLich.getModel(); 
        model = (DefaultTableModel)jTableNhanVien.getModel();
          try {
            con = ketNoi(); 
        } catch (Exception e) {
            System.out.println(e);
        }
          fill_idDatlich(); 
          fill_idnhanvien();
          
          showTableNhanvien(); 
          showTableDatLich();
         
          jTableNhanVien.setRowHeight(40); 
          jTableDatLich.setRowHeight(40); 
          
         choiceIDNhanVien.setVisible(false); 
        choiceID_Datlich.setVisible(false);
        jLabel4.setVisible(false); 
        jLabel6.setVisible(false);
        
    }

  
   public void showTableNhanvien(){
        try{
         
        java.sql.Connection con = ketNoi(); 

        PreparedStatement ps = con.prepareStatement("SELECT id_nhanvien, fullname_nhanvien FROM nhanvien");
        
        java.sql.ResultSet rs=ps.executeQuery(); //chạy câu lệnh sql trên
        DefaultTableModel tm = (DefaultTableModel)jTableNhanVien.getModel(); 
       
        tm.setRowCount(0); 
        while(rs.next()){  
            Object o[]={rs.getInt("id_nhanvien"), rs.getString("fullname_nhanvien")};
           
             tm.addRow(o); 
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e); 
        }
    } 
    public void showTableDatLich(){
        try{
          
        java.sql.Connection con = ketNoi();
          
        PreparedStatement ps = con.prepareStatement("SELECT dl.id_datlich, kh.ten_khachhang, tc.name_thucung, tc.loaidongvat_thucung, dl.trieuchung_datlich "
        
                + "from datlich as dl LEFT JOIN khachhang AS kh "
                + "ON dl.id_khachhang = kh.id_khachhang "
                + "LEFT JOIN thucung AS tc "
                + "ON dl.id_thucung_datlich = tc.id_thucung");  
           
        ResultSet rs= ps.executeQuery(); 
        DefaultTableModel tm = (DefaultTableModel)jTableDatLich.getModel();
       
        tm.setRowCount(0); 
        while(rs.next()){ 
            Object o[]={rs.getInt("dl.id_datlich"), rs.getString("kh.ten_khachhang"), rs.getString("tc.name_thucung"), rs.getString("tc.loaidongvat_thucung"), rs.getString("dl.trieuchung_datlich")};
             
             tm.addRow(o);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    } 
 private void fill_idDatlich(){
     try{
         String sql = "select datlich.id_datlich from datlich"; 
        
         pst=con.prepareStatement(sql); 
         rs=pst.executeQuery(); 
         
         while(rs.next()){ 
       
             String name = rs.getString("id_datlich");
                   
             choiceID_Datlich.addItem(name); 
         }
         
     }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
     }
 }
 private void fill_idnhanvien(){
     try{
         String sql = "select nhanvien.id_nhanvien from nhanvien";
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         
         while(rs.next()){
             String name = rs.getString("id_nhanvien");
             choiceIDNhanVien.addItem(name);
         }
         
     }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
     }
    
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        choiceIDNhanVien = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();
        choiceID_Datlich = new java.awt.Choice();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldGiaTien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNameGuest = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNameNV = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSearchDatLich = new javax.swing.JTextField();
        jTextFieldSearchNhanVien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldCachchua = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDatLich = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID nhân viên chăm sóc");

        choiceIDNhanVien.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID đặt lịch");

        choiceID_Datlich.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cách chữa");

        jTextFieldGiaTien.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTextFieldGiaTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldGiaTienKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Giá tiền");

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 47)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 0));
        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(255, 255, 153));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 0, 47)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(204, 204, 0));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 54)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.setToolTipText("");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên khách hàng đặt lịch");

        jLabelNameGuest.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabelNameGuest.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên nhân viên");

        jLabelNameNV.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabelNameNV.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tìm kiếm theo đặt lịch");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tìm kiếm theo nhân viên");
        jLabel7.setToolTipText("");

        jTextFieldSearchDatLich.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTextFieldSearchDatLich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchDatLichKeyTyped(evt);
            }
        });

        jTextFieldSearchNhanVien.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTextFieldSearchNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchNhanVienKeyTyped(evt);
            }
        });

        jTextFieldCachchua.setColumns(20);
        jTextFieldCachchua.setFont(new java.awt.Font("Monospaced", 0, 32)); // NOI18N
        jTextFieldCachchua.setRows(5);
        jScrollPane1.setViewportView(jTextFieldCachchua);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64)
                        .addComponent(jLabelNameGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSearchDatLich, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8)))
                                .addGap(91, 91, 91)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                                    .addComponent(choiceID_Datlich, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldGiaTien)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(68, 68, 68)
                                .addComponent(choiceIDNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(138, 138, 138)
                                .addComponent(jLabelNameNV, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(188, 188, 188))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButtonBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSearchNhanVien)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButtonBack)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(choiceIDNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(choiceID_Datlich, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNameGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNameNV, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButtonReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldSearchDatLich, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSearchNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(110, 89, 222));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 54)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thông tin thêm chăm sóc");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Chăm Sóc/Thêm Chăm Sóc");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(jLabel9)))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jTableDatLich.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTableDatLich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id đặt lịch", "tên khách", "tên thú cưng", "Loài thú cưng", "Triệu chứng"
            }
        ));
        jTableDatLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDatLichMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDatLich);

        jTableNhanVien.setFont(new java.awt.Font("Tahoma", 0, 37)); // NOI18N
        jTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID nhân viên", "Tên nhân viên"
            }
        ));
        jTableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
  
        jTextFieldGiaTien.setText("");
        jTextFieldCachchua.setText("");
        jLabelNameGuest.setText("");
        jLabelNameNV.setText("");
        jTextFieldSearchDatLich.setText("");
        jTextFieldSearchNhanVien.setText("");
//       
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        new Frame_TimeCare_Information().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Frame_TimeCare_Add addtimetocare = new Frame_TimeCare_Add();
        
        
        String id_nhanvienchamsoc = choiceIDNhanVien.getSelectedItem().toString(); 
    
        String id_datlich = choiceID_Datlich.getSelectedItem().toString();
        String giaTien = jTextFieldGiaTien.getText();
        String CachChua = jTextFieldCachchua.getText();
        
        
        
        ChamSoc chamsoc = new ChamSoc(giaTien, CachChua, id_nhanvienchamsoc,  id_datlich);
       
        if(jTextFieldCachchua.getText().trim().isEmpty() 
       
                || jTextFieldGiaTien.getText().trim().isEmpty()
                 ){
           JOptionPane.showMessageDialog(addtimetocare, "Chưa điền đầy đủ");
           
        }else{
        JOptionPane.showMessageDialog(addtimetocare, "Thêm thành công!!. Sẽ Chuyển Trang trong 2 giây nữa.");
        try {
            Thread.sleep(2000); 
        } catch (InterruptedException ex) {
            Logger.getLogger(Frame_TimeCare_Add.class.getName()).log(Level.SEVERE, null, ex);
        }
          java.util.Date date=new java.util.Date(); //tạo đối tượng date

             java.sql.Date sqlDate=new java.sql.Date(date.getTime()); 
             
             String sql = "INSERT INTO `chamsoc`(`thoigiankethuc_chamsoc`,`price_chamsoc`, `cachchua_chamsoc`, `idnhanvien_chamsoc`,`id_datlich`) VALUES (?,?,?,?,?)";
             
             String sql2 = "UPDATE `ql_thucungcare`.`datlich` SET`type`=3  WHERE id_datlich='"+chamsoc.getId_datlich()+"'";

             try{
                 pst = con.prepareStatement(sql);
                 //chuẩn bị phương thức sql                  
                    pst.setDate(1, sqlDate);
  
                    pst.setString(2, chamsoc.getPrice_cham_soc());
                    pst.setString(3, chamsoc.getCachchua_chamsoc());
                     pst.setString(4, chamsoc.getId_nhanvienchamsoc());
                     pst.setString(5, chamsoc.getId_datlich());
                    pst.executeUpdate();
                    PreparedStatement pst1 = con.prepareStatement(sql2);
                    pst1.executeUpdate();
             }catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
    }
        new Frame_TimeCare_Information().setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldGiaTienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGiaTienKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){ 

            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldGiaTienKeyTyped

    private void jTableDatLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDatLichMouseClicked
        // TODO add your handling code here:
          int index=jTableDatLich.getSelectedRow(); 
   
             TableModel model=jTableDatLich.getModel(); 
   
        choiceID_Datlich.select(model.getValueAt(index, 0).toString());
       
        jLabelNameGuest.setText(model.getValueAt(index, 1).toString());
        
    }//GEN-LAST:event_jTableDatLichMouseClicked

    private void jTableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhanVienMouseClicked
        // TODO add your handling code here:
        int index=jTableNhanVien.getSelectedRow();
             TableModel model=jTableNhanVien.getModel();
        choiceIDNhanVien.select(model.getValueAt(index, 0).toString());
        jLabelNameNV.setText(model.getValueAt(index, 1).toString());
    }//GEN-LAST:event_jTableNhanVienMouseClicked
private void FilterDatLich(String query){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model1); 
        jTableDatLich.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
private void FilterNhanVien(String query){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model); 
        jTableNhanVien.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    private void jTextFieldSearchNhanVienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchNhanVienKeyTyped
        // TODO add your handling code here:
         String query = jTextFieldSearchNhanVien.getText();
        if(query != null && query.length() > 0){
            FilterNhanVien(query);
        }
    }//GEN-LAST:event_jTextFieldSearchNhanVienKeyTyped

    private void jTextFieldSearchDatLichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchDatLichKeyTyped
        // TODO add your handling code here:
         String query = jTextFieldSearchDatLich.getText();
        if(query != null && query.length() > 0){
            FilterDatLich(query);
        }
    }//GEN-LAST:event_jTextFieldSearchDatLichKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_TimeCare_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_TimeCare_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_TimeCare_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_TimeCare_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_TimeCare_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Choice choiceIDNhanVien;
    private java.awt.Choice choiceID_Datlich;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNameGuest;
    private javax.swing.JLabel jLabelNameNV;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDatLich;
    private javax.swing.JTable jTableNhanVien;
    private javax.swing.JTextArea jTextFieldCachchua;
    private javax.swing.JTextField jTextFieldGiaTien;
    private javax.swing.JTextField jTextFieldSearchDatLich;
    private javax.swing.JTextField jTextFieldSearchNhanVien;
    // End of variables declaration//GEN-END:variables
}
